apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcm
  namespace: kube-system
spec:
  project: hcm
  source:
    repoURL: https://github.com/panikaa/gitops-cluster-config.git
    targetRevision: main
    path: apps/hcm/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: hcm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true